<?php
/**
 * Email:zhaojunlike@gmail.com
 * Date: 5/30/2017
 * Time: 2:28 PM
 */

namespace app\index\controller;


class Auth extends Base
{

    protected $current_uid = null;

    protected function _initialize()
    {

        //checkLogin
        $agentId = session('login_uid');
        if (!$agentId) {
            $this->redirect("protal/login");
            exit();
        }
        $this->current_uid = $agentId;
        parent::_initialize(); // TODO: Change the autogenerated stub

    }
}